locale_ruRU
trickerer/Trinity-Bots pull request #242
Opened 2022-11-10 19:20 UTC by xBarselonx

trickerer, привет!
Попробовал сделать русскую локализацию меню ботов. Можно включить мои изменения в твой репозиторий? Делаю первый раз в своей жизни)). Посмотри, что не так.

2022-11-12 02:57 UTC, trickerer commented
Что с текстами 70001-70011, 70101-70108, 70201-70204?

2022-11-12 05:06 UTC, xBarselonx commented
> Что с текстами [70001-70011](tel:70001-70011), [70101-70108](tel:70101-70108), [70201-70204](tel:70201-70204)?

Забыл про них, сегодня постараюсь доделать. 
trickerer, можно попросить тебя просмотреть мой перевод, т.к. с английским у меня не очень?

2022-11-12 08:20 UTC, trickerer commented
> trickerer, можно попросить тебя просмотреть мой перевод

Я уже накидал комментов

2022-11-12 10:59 UTC, xBarselonx commented
> Что с текстами 70001-70011, 70101-70108, 70201-70204?

готово

2022-11-12 11:04 UTC, xBarselonx commented
> > trickerer, можно попросить тебя просмотреть мой перевод
> 
> Я уже накидал комментов

ок

2022-11-14 03:52 UTC, xBarselonx commented
trickerer, привет! Ко мне еще есть вопросы по локализации?

2022-11-14 04:34 UTC, trickerer requested changes
Я и не заметил что замечания в файлах не видны

2022-11-18 05:13 UTC, trickerer commented
https://github.com/trickerer/Trinity-Bots/commit/fec63d06cfb4b274e6df330a2e9cfdaa1359ec33

2022-11-18 05:13 UTC, closed without merging